#server:
#  port: 8081
#
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/productdb
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect

spring:
  application:
    name: product-service

  config:
    import: optional:configserver:http://localhost:8888

logging:
  level:
    root: INFO


